# ziye
# github地址  https://github.com/6Svip120apk69
# TG频道地址  https://t.me/ziyescript
# TG交流群    https://t.me/joinchat/AAAAAE7XHm-q1-7Np-tF3g
# boxjs链接   https://raw.githubusercontent.com/6Svip120apk69/gitee_q8qsTAUA_cThxc1RBVUE/main/Task/ziye.boxjs.json



# ⚠️⚠️⚠️特别重要,务必进行替换操作，不得使用原作者地址

# 具体方法请看: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions



name: 哈喽短视频

on:
  workflow_dispatch:
  schedule:
     - cron: '27 4,8 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      HLDSPURL: ${{ secrets.HLDSPURL }}
      HLDSPHD: ${{ secrets.HLDSPHD }}
        
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/pipi242526/QuantumultX.git ~/QuantumultX
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.HLDSPHD
        run: |
          cd ~/QuantumultX
          git checkout JavaScript
          npm install
      - name: '运行 【哈喽短视频】'
        if: env.HLDSPHD
        run: |
          cd ~/QuantumultX
          node Task/hldsp.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
