name: 燃旅视频

on:
  workflow_dispatch:
  schedule:
     - cron: '5,35 9-22 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        RLURL: ${{ secrets.RLURL }}
        RLHEADER: ${{ secrets.RLHEADER }}
        RLBODY: ${{ secrets.RLBODY }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/LiuYuanwork/Node-Script.git ~/Node-Script
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.RLURL
        run: |
          cd ~/Node-Script
          npm install
      - name: '运行 【燃旅视频】'
        if: env.RLURL
        run: |
          cd ~/Node-Script
          node Task/ranlv.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
