name: 书旗小说
on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '5 2,6,10 * * *'
jobs:
  build: 
    runs-on: ubuntu-latest       
    steps:
      
      - name: Checkout
        run: |
          git clone https://github.com/pipi242526/QuantumultX.git ~/QuantumultX
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
 
         cd ~/js
          npm install
          npm install cron
          npm install request
          curl ipinfo.io/json
      
      - name: '【书旗小说】'
        run: |
          cd ~/QuantumultX 
          node Task/sqxs.js


